### PR TITLE
Add code for submitting exit questionnaire

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/nhs-ngs/jellypy/8)

### CODE REVIEW

**Comment by andyb3** [comment]
Also now added function for downloading summary of findings html

**Comment by andyb3** [comment]
Yep splitting it out sounds like a good idea, will let you know when it's done

**Comment by andyb3** [comment]
> This workflow will work fine to close cases with negative findings fully. It might be nice to extend to allow for the exit questionnaire to be posted without making the clinical report (e.g. for when there are a number of cases with empty summaries of findings which require closing).
> This would fit the situation where GMCs which don't automatically close cases with no tier 1/2 variants might look into Exomiser etc. and manually generate the summary of findings while on the page. These can then be bulk-closed using an exit questionnaire-only generation

@MattWellie I have now split this out into separate scripts for the clinical report and exit questionnaire (and brought in commits from master made since this was originally raised).

Hopefully should now be good to go, if you don't mind taking a look?

**Comment by MattWellie** [comment]
@andyb3  Nice, I like it. Should fit both use-cases

**Pull request merged**
