### PR TITLE
Update pyCIPAPI to use GMS/100K auth endpoint. Update imports in scripts.

### PR DESCRIPTION
**Pull request by NMNS93**
* Use new GMS/100K authentication endpoint
* Add jellypy namespace to script imports.
* Move vcfs_compare.py to scripts/

---
This change is [Reviewable](https://reviewable.io/reviews/nhs-ngs/jellypy/24)

### CODE REVIEW

**Comment by s-boardman** [comment]
That looks good for the new method. Given the authentication change is being pushed back to April perhaps it's worth supporting the legacy method for this version and deprecating it once the new method is implemented, validated, and stable?

**Comment by NMNS93** [comment]
> That looks good for the new method. Given the authentication change is being pushed back to April perhaps it's worth supporting the legacy method for this version and deprecating it once the new method is implemented, validated, and stable?

Yeah that's really sensible! What do you think of adding an argument like this
`AuthenticatedCIPAPISession(..., legacy_auth=True)`. True could be the default for now, then we could remove it once GMS is live?

**Comment by s-boardman** [comment]
> 
> 
> > That looks good for the new method. Given the authentication change is being pushed back to April perhaps it's worth supporting the legacy method for this version and deprecating it once the new method is implemented, validated, and stable?
> 
> Yeah that's really sensible! What do you think of adding an argument like this
> `AuthenticatedCIPAPISession(..., legacy_auth=True)`. True could be the default for now, then we could remove it once GMS is live?

I'd copy what the Gel2MDT method looks like tbh, keeps it a bit more standard? They've got a flag for using the active directory ([see here](https://github.com/NHS-NGS/GeL2MDT/blob/active_dirctory_support/gelweb/gel2mdt/api_utils/poll_api.py#L88)) that seems like a lgical way of doing things.

**Comment by NMNS93** [comment]
Nice one, I'll add something similar later this week and nudge again.

**Comment by s-boardman** [comment]
Looks good to me. Top work. :100:

**Pull request merged**
